import { Request, Response } from 'express';

/** GET /api — grouped route index (see route files for full detail). */
const CATALOG = {
  service: 'oceanbazar-api',
  version: '1',
  endpoints: {
    meta: ['GET /api', 'GET /api/health'],
    catalog: [
      'GET /api/categories',
      'GET /api/categories/:id',
      'GET /api/products',
      'GET /api/products/compare',
      'GET /api/products/:id',
      'GET /api/brands',
      'GET /api/brands/:slugOrId',
    ],
    cart: [
      'GET /api/cart',
      'POST /api/cart/add',
      'PUT /api/cart/update',
      'DELETE /api/cart/remove/:productId',
      'POST /api/cart/apply-coupon',
      'POST /api/cart/apply-ob-points',
    ],
    orders: ['POST /api/orders/place', 'GET /api/orders', 'GET /api/orders/:id', 'GET /api/orders/:id/tracking', 'POST /api/orders/:id/cancel'],
    payments: [
      'POST /api/payments/bkash/initiate',
      'POST /api/payments/bkash/confirm',
      'POST /api/payments/nagad/initiate',
      'POST /api/payments/nagad/confirm',
      'POST /api/payments/rocket/initiate',
      'POST /api/payments/upay/initiate',
      'POST /api/payments/sslcommerz/initiate',
      'POST /api/payments/sslcommerz/ipn',
    ],
    obPoints: ['GET /api/ob-points/tiers', 'GET /api/ob-points/balance', 'GET /api/ob-points/ledger', 'POST /api/ob-points/redeem'],
    reviews: ['GET /api/reviews/product/:productId', 'GET /api/reviews/me', 'POST /api/reviews'],
    customers: ['GET /api/customers/me', 'PUT /api/customers/me'],
    profile: [
      'GET /api/profile',
      'PUT /api/profile',
      'GET /api/profile/addresses',
      'POST /api/profile/addresses',
      'PUT /api/profile/addresses/:id',
      'DELETE /api/profile/addresses/:id',
    ],
    tickets: ['POST /api/tickets', 'GET /api/tickets', 'GET /api/tickets/:id', 'POST /api/tickets/:id/messages'],
    delivery: ['GET /api/delivery/track/:trackingNumber', 'GET /api/delivery/carriers', 'POST /api/delivery/webhook/:carrier', 'GET /api/delivery/my-shipments'],
    auth: [
      'POST /api/auth/register',
      'POST /api/auth/send-otp',
      'POST /api/auth/verify-otp',
      'POST /api/auth/login',
      'POST /api/auth/refresh',
      'GET /api/auth/me',
      'POST /api/auth/logout',
      'POST /api/auth/forgot-password',
      'POST /api/auth/reset-password',
      'PUT /api/auth/change-password',
      'GET /api/auth/social/google',
      'GET /api/auth/social/google/callback',
      'GET /api/auth/social/facebook',
      'GET /api/auth/social/facebook/callback',
    ],
    admin: [
      'POST /api/admin/auth/login',
      'GET /api/admin/auth/me',
      'GET /api/admin/overview',
      'GET /api/admin/products',
      'POST /api/admin/products',
      'DELETE /api/admin/products/:id',
      'GET /api/admin/categories',
      'POST /api/admin/categories',
      'GET /api/admin/orders',
      'PUT /api/admin/orders/:id/status',
      'POST /api/admin/shipments',
      'GET /api/admin/customers',
      'PATCH /api/admin/reviews/:id',
      'GET /api/admin/analytics/dashboard',
      'GET /api/admin/studio/catalog-tree',
      'GET /api/admin/studio/brands',
      'GET /api/admin/studio/products/:id',
      'PUT /api/admin/studio/products/:id',
      '… /api/admin/studio/* (categories, coupons, shipments)',
      '… /api/admin/file-import/*',
      '… /api/admin/ob-points/*',
      '… /api/admin/tickets/*',
    ],
  },
};

export function apiCatalogHandler(_req: Request, res: Response): void {
  res.json(CATALOG);
}
