/** Copied from frontend/messages — keep in sync when policy/marketing copy changes. */
const COPY = {
  "en": {
    "marketing": {
      "heroTitle": "Bangladesh's Retail & Wholesale Marketplace",
      "heroSub": "One platform for everyday shoppers and bulk buyers — secure payments, nationwide logistics, and automatic wholesale pricing for qualified businesses.",
      "shopNow": "Shop Now",
      "wholesaleHub": "Wholesale Hub",
      "whyTitle": "Why OceanBazar?",
      "whySub": "Built specifically for the Bangladeshi market — retail and wholesale in a single, unified experience.",
      "feat1Title": "Made for Bangladesh",
      "feat1Body": "Currency in BDT, Bangla + English UI, local payment gateways — everything built for the local market.",
      "feat2Title": "Auto Volume Pricing",
      "feat2Body": "Tiered discounts apply automatically as you add more items. No coupon codes needed.",
      "feat3Title": "Order Protection",
      "feat3Body": "Every order is covered. Dispute resolution, money-back guarantee, and verified fulfillment.",
      "feat4Title": "OB Points Rewards",
      "feat4Body": "Earn 1 OB Point per ৳1 spent. Redeem for discounts. Bronze, Silver, and Gold tiers.",
      "logisticsTitle": "Bangladesh-Focused Logistics",
      "logisticsSub": "Delivery coverage across all 64 districts. We partner with reliable couriers to ensure your order reaches you — Dhaka or Sylhet, Cox's Bazar or Rajshahi.",
      "log1": "2–5 business days standard delivery",
      "log2": "Same-day dispatch for in-stock items",
      "log3": "Real-time tracking via order timeline",
      "log4": "Hassle-free return & exchange policy",
      "stat1Label": "64 Districts",
      "stat1Sub": "Nationwide coverage",
      "stat2Label": "2–5 Days",
      "stat2Sub": "Standard delivery",
      "stat3Label": "Live Tracking",
      "stat3Sub": "Order timeline updates",
      "stat4Label": "Easy Returns",
      "stat4Sub": "Within policy window",
      "paymentsTitle": "Secure Payments",
      "paymentsSub": "All transactions are encrypted. Choose from Bangladesh's most popular payment methods — mobile banking, cards, or cash on delivery.",
      "protectionTitle": "What we protect",
      "protect1": "End-to-end encrypted payment flow",
      "protect2": "No card details stored on our servers",
      "protect3": "Verified seller and product authenticity",
      "protect4": "Full refund for undelivered orders",
      "protect5": "Dispute resolution within 5 business days",
      "protect6": "COD available for orders up to ৳5,000",
      "deliveryTitle": "Fast & Reliable Delivery",
      "deliverySub": "We work with trusted courier partners to ensure your orders arrive on time. Real-time updates keep you informed at every step.",
      "del1Title": "Same-Day Dispatch",
      "del1Body": "Orders placed before 12pm are dispatched the same business day.",
      "del2Title": "2–5 Day Delivery",
      "del2Body": "Standard nationwide delivery. Dhaka metro may arrive faster.",
      "del3Title": "Delivery Support",
      "del3Body": "Missed delivery? Our support team coordinates redelivery for you.",
      "wholesaleTitle": "Wholesale Opportunities",
      "wholesaleSub": "Whether you run a shop, source for resale, or buy in bulk for your business — OceanBazar wholesale gives you lower prices automatically.",
      "wPoint1": "Automatic wholesale price at MOQ (25+ units)",
      "wPoint2": "Up to 8% additional volume discount on wholesale base",
      "wPoint3": "Separate pricing tier from retail — not just a coupon",
      "wPoint4": "Priority order fulfillment for large orders",
      "wPoint5": "Business invoice support",
      "applyWholesale": "Apply for Wholesale",
      "browseProducts": "Browse Products",
      "whoTitle": "Who is it for?",
      "who1Title": "Retailers & Resellers",
      "who1Body": "Source products at wholesale rates and maximize your margin.",
      "who2Title": "Growing Businesses",
      "who2Body": "Scale purchasing as your business grows — pricing scales with you.",
      "who3Title": "Corporate Buyers",
      "who3Body": "Bulk procurement for offices, institutions, and enterprises.",
      "ctaTitle": "Start shopping on OceanBazar",
      "ctaSub": "Retail or wholesale — one account, one platform, the best prices in Bangladesh."
    },
    "support": {
      "title": "Support Center",
      "subtitle": "Find answers quickly or get in touch with our team. We respond to all tickets within 1–2 business days.",
      "openTicket": "Open a Ticket",
      "startReturn": "Start a Return",
      "helpTitle": "What do you need help with?",
      "orderIssues": "Order Issues",
      "orderIssuesSub": "Missing item, wrong product, delayed delivery",
      "returnsRefunds": "Returns & Refunds",
      "returnsRefundsSub": "Return eligibility, refund status, exchange",
      "paymentProblems": "Payment Problems",
      "paymentProblemsSub": "Failed payment, double charge, refund timing",
      "deliveryTracking": "Delivery Tracking",
      "deliveryTrackingSub": "Track your shipment, rescheduling, courier contact",
      "accountPoints": "Account & OB Points",
      "accountPointsSub": "Login issues, points balance, tier status",
      "warrantyClaims": "Warranty Claims",
      "warrantyClaimsSub": "Product warranty, defect reporting, service",
      "disputeProcess": "Dispute Process",
      "disputeProcessSub": "How we handle order disputes",
      "returnProcess": "Return Process",
      "returnProcessSub": "Step-by-step return flow",
      "disputeStep1Title": "Open a ticket",
      "disputeStep1Sub": "Include your Order ID and describe the issue clearly.",
      "disputeStep2Title": "Team review",
      "disputeStep2Sub": "We investigate within 1–2 business days and may request evidence.",
      "disputeStep3Title": "Decision",
      "disputeStep3Sub": "We notify you of the outcome — refund, replacement, or explanation.",
      "disputeStep4Title": "Resolution",
      "disputeStep4Sub": "Approved actions are executed within the stated timelines.",
      "returnStep1Title": "Check eligibility",
      "returnStep1Sub": "7-day window from delivery. Item must be unused and in original packaging.",
      "returnStep2Title": "Submit request",
      "returnStep2Sub": "Go to My Orders → select item → Return / Dispute.",
      "returnStep3Title": "Pickup arranged",
      "returnStep3Sub": "Once approved, courier pickup is arranged within 1–3 days.",
      "returnStep4Title": "Inspection & refund",
      "returnStep4Sub": "After inspection passes, refund is initiated within 3 business days.",
      "openDisputeTicket": "Open a Dispute Ticket",
      "startReturnRequest": "Start a Return Request",
      "timelinesTitle": "Response & Resolution Timelines",
      "colRequestType": "Request type",
      "colInitialResponse": "Initial response",
      "colResolution": "Resolution",
      "row1Type": "General support query",
      "row1Response": "1–2 business days",
      "row1Resolution": "2–5 business days",
      "row2Type": "Order dispute",
      "row2Response": "1–2 business days",
      "row2Resolution": "3–7 business days",
      "row3Type": "Return request review",
      "row3Response": "1–2 business days",
      "row3Resolution": "5–10 business days",
      "row4Type": "Refund (mobile wallet)",
      "row4Response": "1 business day",
      "row4Resolution": "1–3 business days",
      "row5Type": "Refund (card/bank)",
      "row5Response": "1 business day",
      "row5Resolution": "5–10 business days",
      "row6Type": "Warranty claim",
      "row6Response": "1–2 business days",
      "row6Resolution": "7–21 business days",
      "row7Type": "Payment failure trace",
      "row7Response": "1 business day",
      "row7Resolution": "2–5 business days",
      "faqTitle": "Frequently Asked Questions",
      "faq1q": "How do I return an item?",
      "faq1a": "Go to My Orders, select the order, and tap \"Return / Dispute\". Fill in the reason and submit. Our team reviews within 1–2 business days.",
      "faq2q": "When will I get my refund?",
      "faq2a": "After your return is approved and the item passes inspection, refunds are processed within 1–3 business days for mobile wallets, or 5–10 days for card/bank payments.",
      "faq3q": "My order hasn't arrived. What should I do?",
      "faq3a": "Check your order tracking timeline first. If the estimated delivery window has passed, open a support ticket with your Order ID and we'll investigate.",
      "faq4q": "Can I change my delivery address after placing an order?",
      "faq4a": "Address changes are only possible before dispatch. Contact support immediately with your Order ID. We cannot change the address once the order is with the courier.",
      "faq5q": "How do I apply for wholesale access?",
      "faq5a": "Visit the Wholesale Hub page and fill in the application form. Our team reviews applications within 2–3 business days.",
      "faq6q": "What payment methods are accepted?",
      "faq6a": "We accept bKash, Nagad, Rocket, Upay, SSLCommerz (card & internet banking), and Cash on Delivery (up to ৳5,000).",
      "faq7q": "My payment failed but money was deducted. What happens?",
      "faq7a": "Failed payment deductions are auto-reversed by the payment provider within 3–5 business days. If not, open a ticket with your transaction reference number.",
      "faq8q": "How do OB Points work?",
      "faq8a": "You earn 1 OB Point for every ৳1 spent. Points can be redeemed for discounts at checkout. Bronze, Silver, and Gold tiers offer increasing redemption limits.",
      "stillNeedHelp": "Still need help?",
      "supportTicketsTitle": "Support Tickets",
      "supportTicketsDesc": "Open a ticket for order disputes, payment issues, or product complaints. Full message history stored.",
      "openTicketCta": "Open ticket →",
      "policyDocsTitle": "Policy Documents",
      "policyDocsDesc": "Read our Return, Refund, Shipping, Warranty, and Terms policies for complete details.",
      "readPoliciesCta": "Read policies →"
    },
    "contact": {
      "eyebrow": "Get in touch",
      "title": "Contact Ocean Bazar",
      "intro": "Questions about orders, wholesale, or partnerships? Our team is here to help across Bangladesh.",
      "visionEyebrow": "Our vision",
      "visionTitle": "Building Ocean Bazar",
      "leadershipEyebrow": "Leadership",
      "leadershipTitle": "Our leadership team",
      "buildingAlt": "Ocean Bazar warehouse and logistics hub",
      "aboutTitle": "About Ocean Bazar",
      "aboutBody": "Ocean Bazar is Bangladesh's trusted retail and wholesale ecommerce platform — beyond borders, built for generations. We connect customers and businesses to authentic, high-quality products with reliable nationwide delivery.",
      "aboutBody2": "From our fulfillment hub we serve retail shoppers, wholesale buyers, and brand partners with transparent pricing, secure payments, and dedicated support.",
      "reachTitle": "Contact details",
      "addressLabel": "Address",
      "contactEmailLabel": "Contact email",
      "businessEmailLabel": "Business inquiry email",
      "phoneLabel": "Contact phone",
      "chatCta": "Live chat",
      "businessCta": "Business inquiries",
      "supportCta": "Support center"
    },
    "business": {
      "heroTag": "Business & Partnerships",
      "title": "Partner With OceanBazar",
      "subtitle": "Whether you're looking for bulk procurement, corporate gifting, reseller partnerships, or brand collaboration — we'd love to hear from you.",
      "whyTitle": "Why Partner With Us?",
      "whySub": "OceanBazar is built to support businesses of all sizes across Bangladesh.",
      "feat1Title": "Nationwide Reach",
      "feat1Body": "Access a logistics network spanning all 64 districts of Bangladesh with reliable last-mile delivery.",
      "feat2Title": "Wholesale Pricing",
      "feat2Body": "Automatic volume-based discounts — the more you order, the more you save. No negotiation needed.",
      "feat3Title": "Verified Marketplace",
      "feat3Body": "Every seller is verified. Products are quality-checked. Full buyer protection on every order.",
      "feat4Title": "Dedicated Support",
      "feat4Body": "Business accounts get a priority support queue with faster response times for critical issues.",
      "feat5Title": "Secure Payments",
      "feat5Body": "All transactions encrypted end-to-end. Pay via bKash, Nagad, SSLCommerz, or bank transfer.",
      "feat6Title": "Custom Solutions",
      "feat6Body": "Need branded packaging, scheduled deliveries, or custom catalogs? We build solutions around your needs.",
      "ctaTitle": "Ready to grow together?",
      "ctaSub": "Fill in the form below and our business team will reach out within 24–48 hours.",
      "inquiryEmailLabel": "Business inquiry email",
      "contactPageCta": "General contact details",
      "formTitle": "Send us your inquiry",
      "name": "Your name",
      "email": "Email address",
      "company": "Company / Organization",
      "phone": "Phone number",
      "businessType": "Business type",
      "businessTypes": {
        "retailer": "Retailer / Reseller",
        "corporate": "Corporate buyer",
        "brand": "Brand / Manufacturer",
        "wholesale": "Wholesale distributor",
        "other": "Other"
      },
      "message": "Tell us about your needs",
      "messagePlaceholder": "Describe your business, expected order volume, product interests, or partnership idea…",
      "submit": "Submit Inquiry",
      "success": "Thank you! Our business team will contact you within 24–48 hours.",
      "stat1": "500+",
      "stat1Label": "Active business partners",
      "stat2": "64",
      "stat2Label": "Districts covered",
      "stat3": "24h",
      "stat3Label": "Average response time",
      "stat4": "98%",
      "stat4Label": "Partner satisfaction"
    }
  },
  "bn": {
    "marketing": {
      "heroTitle": "বাংলাদেশের খুচরা ও পাইকারি মার্কেটপ্লেস",
      "heroSub": "সাধারণ ক্রেতা ও বাল্ক বায়ারদের জন্য একটি প্ল্যাটফর্ম — নিরাপদ পেমেন্ট, সারাদেশে লজিস্টিক্স ও যোগ্য ব্যবসায়ীদের জন্য স্বয়ংক্রিয় পাইকারি মূল্য।",
      "shopNow": "এখনই কিনুন",
      "wholesaleHub": "পাইকারি হাব",
      "whyTitle": "কেন OceanBazar?",
      "whySub": "বাংলাদেশের বাজারের জন্য বিশেষভাবে তৈরি — একটি প্ল্যাটফর্মে খুচরা ও পাইকারি।",
      "feat1Title": "বাংলাদেশের জন্য তৈরি",
      "feat1Body": "BDT-তে মূল্য, বাংলা + ইংরেজি UI, স্থানীয় পেমেন্ট গেটওয়ে — সব কিছু স্থানীয় বাজারের জন্য।",
      "feat2Title": "স্বয়ংক্রিয় ভলিউম মূল্য",
      "feat2Body": "আরও পণ্য যোগ করলে টিয়ার্ড ছাড় স্বয়ংক্রিয়ভাবে প্রযোজ্য হয়। কোনো কুপন কোড লাগবে না।",
      "feat3Title": "অর্ডার সুরক্ষা",
      "feat3Body": "প্রতিটি অর্ডার সুরক্ষিত। বিবাদ সমাধান, মানি-ব্যাক গ্যারান্টি ও যাচাইকৃত পূরণ।",
      "feat4Title": "OB পয়েন্ট পুরস্কার",
      "feat4Body": "প্রতি ৳১ খরচে ১ OB পয়েন্ট অর্জন করুন। ছাড়ের জন্য রিডিম করুন। ব্রোঞ্জ, সিলভার ও গোল্ড স্তর।",
      "logisticsTitle": "বাংলাদেশ-কেন্দ্রিক লজিস্টিক্স",
      "logisticsSub": "সব ৬৪ জেলায় ডেলিভারি। আমরা নির্ভরযোগ্য কুরিয়ারের সাথে কাজ করি — ঢাকা বা সিলেট, কক্সবাজার বা রাজশাহী।",
      "log1": "২–৫ কার্যদিনে স্ট্যান্ডার্ড ডেলিভারি",
      "log2": "স্টকে থাকা পণ্যে একই দিনে ডিসপ্যাচ",
      "log3": "অর্ডার টাইমলাইনের মাধ্যমে রিয়েল-টাইম ট্র্যাকিং",
      "log4": "ঝামেলামুক্ত রিটার্ন ও এক্সচেঞ্জ পলিসি",
      "stat1Label": "৬৪ জেলা",
      "stat1Sub": "সারাদেশে কভারেজ",
      "stat2Label": "২–৫ দিন",
      "stat2Sub": "স্ট্যান্ডার্ড ডেলিভারি",
      "stat3Label": "লাইভ ট্র্যাকিং",
      "stat3Sub": "অর্ডার টাইমলাইন আপডেট",
      "stat4Label": "সহজ রিটার্ন",
      "stat4Sub": "পলিসির মধ্যে",
      "paymentsTitle": "নিরাপদ পেমেন্ট",
      "paymentsSub": "সব লেনদেন এনক্রিপ্টেড। বাংলাদেশের সবচেয়ে জনপ্রিয় পেমেন্ট পদ্ধতি থেকে বেছে নিন।",
      "protectionTitle": "আমরা যা সুরক্ষা দিই",
      "protect1": "এন্ড-টু-এন্ড এনক্রিপ্টেড পেমেন্ট ফ্লো",
      "protect2": "আমাদের সার্ভারে কোনো কার্ডের তথ্য সংরক্ষিত নেই",
      "protect3": "যাচাইকৃত বিক্রেতা ও পণ্যের সত্যতা",
      "protect4": "ডেলিভারি না হলে সম্পূর্ণ রিফান্ড",
      "protect5": "৫ কার্যদিনের মধ্যে বিবাদ সমাধান",
      "protect6": "৳৫,০০০ পর্যন্ত অর্ডারে COD উপলব্ধ",
      "deliveryTitle": "দ্রুত ও নির্ভরযোগ্য ডেলিভারি",
      "deliverySub": "আমরা বিশ্বস্ত কুরিয়ার পার্টনারদের সাথে কাজ করি। রিয়েল-টাইম আপডেট আপনাকে সব ধাপে অবহিত রাখে।",
      "del1Title": "একই দিনে ডিসপ্যাচ",
      "del1Body": "দুপুর ১২টার আগে অর্ডার দিলে একই কার্যদিনে ডিসপ্যাচ হয়।",
      "del2Title": "২–৫ দিনে ডেলিভারি",
      "del2Body": "সারাদেশে স্ট্যান্ডার্ড ডেলিভারি। ঢাকা মেট্রোতে দ্রুত আসতে পারে।",
      "del3Title": "ডেলিভারি সাপোর্ট",
      "del3Body": "ডেলিভারি মিস হয়েছে? আমাদের সাপোর্ট দল পুনরায় ডেলিভারির ব্যবস্থা করে।",
      "wholesaleTitle": "পাইকারি সুযোগ",
      "wholesaleSub": "দোকান চালান, পুনরায় বিক্রির জন্য সোর্স করেন বা ব্যবসার জন্য বাল্কে কিনুন — OceanBazar পাইকারি স্বয়ংক্রিয়ভাবে কম দাম দেয়।",
      "wPoint1": "MOQ (২৫+ ইউনিট) তে স্বয়ংক্রিয় পাইকারি মূল্য",
      "wPoint2": "পাইকারি বেসে ৮% পর্যন্ত অতিরিক্ত ভলিউম ছাড়",
      "wPoint3": "খুচরা থেকে আলাদা মূল্য স্তর — শুধু কুপন নয়",
      "wPoint4": "বড় অর্ডারে অগ্রাধিকার পূরণ",
      "wPoint5": "ব্যবসায়িক ইনভয়েস সাপোর্ট",
      "applyWholesale": "পাইকারির জন্য আবেদন করুন",
      "browseProducts": "পণ্য ব্রাউজ করুন",
      "whoTitle": "কাদের জন্য?",
      "who1Title": "খুচরা বিক্রেতা ও রিসেলার",
      "who1Body": "পাইকারি হারে পণ্য সোর্স করুন এবং মার্জিন সর্বোচ্চ করুন।",
      "who2Title": "ক্রমবর্ধমান ব্যবসা",
      "who2Body": "ব্যবসার সাথে সাথে কেনাকাটা বাড়ান — মূল্য আপনার সাথে স্কেল হয়।",
      "who3Title": "কর্পোরেট ক্রেতা",
      "who3Body": "অফিস, প্রতিষ্ঠান ও উদ্যোগের জন্য বাল্ক প্রকিউরমেন্ট।",
      "ctaTitle": "OceanBazar-এ কেনাকাটা শুরু করুন",
      "ctaSub": "খুচরা বা পাইকারি — একটি অ্যাকাউন্ট, একটি প্ল্যাটফর্ম, বাংলাদেশের সেরা দাম।"
    },
    "support": {
      "title": "সাপোর্ট সেন্টার",
      "subtitle": "দ্রুত উত্তর খুঁজুন বা আমাদের দলের সাথে যোগাযোগ করুন। আমরা সব টিকিটে ১–২ কার্যদিনের মধ্যে সাড়া দিই।",
      "openTicket": "টিকিট খুলুন",
      "startReturn": "রিটার্ন শুরু করুন",
      "helpTitle": "আপনার কী সাহায্য দরকার?",
      "orderIssues": "অর্ডার সমস্যা",
      "orderIssuesSub": "পণ্য নেই, ভুল পণ্য, বিলম্বিত ডেলিভারি",
      "returnsRefunds": "রিটার্ন ও রিফান্ড",
      "returnsRefundsSub": "রিটার্ন যোগ্যতা, রিফান্ড স্ট্যাটাস, এক্সচেঞ্জ",
      "paymentProblems": "পেমেন্ট সমস্যা",
      "paymentProblemsSub": "ব্যর্থ পেমেন্ট, দ্বিগুণ চার্জ, রিফান্ডের সময়",
      "deliveryTracking": "ডেলিভারি ট্র্যাকিং",
      "deliveryTrackingSub": "শিপমেন্ট ট্র্যাক করুন, পুনঃনির্ধারণ, কুরিয়ার যোগাযোগ",
      "accountPoints": "অ্যাকাউন্ট ও OB পয়েন্ট",
      "accountPointsSub": "লগইন সমস্যা, পয়েন্ট ব্যালেন্স, স্তর",
      "warrantyClaims": "ওয়ারেন্টি দাবি",
      "warrantyClaimsSub": "পণ্যের ওয়ারেন্টি, ত্রুটি রিপোর্ট, সেবা",
      "disputeProcess": "বিবাদ প্রক্রিয়া",
      "disputeProcessSub": "আমরা কীভাবে অর্ডার বিবাদ সামলাই",
      "returnProcess": "রিটার্ন প্রক্রিয়া",
      "returnProcessSub": "ধাপে ধাপে রিটার্ন ফ্লো",
      "disputeStep1Title": "টিকিট খুলুন",
      "disputeStep1Sub": "আপনার অর্ডার ID এবং সমস্যার বিবরণ স্পষ্টভাবে উল্লেখ করুন।",
      "disputeStep2Title": "দলের পর্যালোচনা",
      "disputeStep2Sub": "আমরা ১–২ কার্যদিনের মধ্যে তদন্ত করব এবং প্রমাণ চাইতে পারি।",
      "disputeStep3Title": "সিদ্ধান্ত",
      "disputeStep3Sub": "আমরা আপনাকে ফলাফল জানাব — রিফান্ড, প্রতিস্থাপন বা ব্যাখ্যা।",
      "disputeStep4Title": "সমাধান",
      "disputeStep4Sub": "অনুমোদিত কার্যক্রম নির্ধারিত সময়সীমার মধ্যে কার্যকর হবে।",
      "returnStep1Title": "যোগ্যতা পরীক্ষা করুন",
      "returnStep1Sub": "ডেলিভারির ৭ দিনের মধ্যে। পণ্য অব্যবহৃত ও মূল প্যাকেজিংয়ে থাকতে হবে।",
      "returnStep2Title": "অনুরোধ জমা দিন",
      "returnStep2Sub": "আমার অর্ডার → পণ্য নির্বাচন করুন → রিটার্ন / বিবাদ।",
      "returnStep3Title": "পিকআপ নির্ধারিত",
      "returnStep3Sub": "অনুমোদিত হলে ১–৩ দিনের মধ্যে কুরিয়ার পিকআপ নির্ধারিত হবে।",
      "returnStep4Title": "পরীক্ষা ও রিফান্ড",
      "returnStep4Sub": "পরীক্ষায় উত্তীর্ণ হলে ৩ কার্যদিনের মধ্যে রিফান্ড শুরু হবে।",
      "openDisputeTicket": "বিবাদ টিকিট খুলুন",
      "startReturnRequest": "রিটার্ন অনুরোধ শুরু করুন",
      "timelinesTitle": "সাড়া ও সমাধানের সময়সীমা",
      "colRequestType": "অনুরোধের ধরন",
      "colInitialResponse": "প্রাথমিক সাড়া",
      "colResolution": "সমাধান",
      "row1Type": "সাধারণ সহায়তা জিজ্ঞাসা",
      "row1Response": "১–২ কার্যদিন",
      "row1Resolution": "২–৫ কার্যদিন",
      "row2Type": "অর্ডার বিবাদ",
      "row2Response": "১–২ কার্যদিন",
      "row2Resolution": "৩–৭ কার্যদিন",
      "row3Type": "রিটার্ন অনুরোধ পর্যালোচনা",
      "row3Response": "১–২ কার্যদিন",
      "row3Resolution": "৫–১০ কার্যদিন",
      "row4Type": "রিফান্ড (মোবাইল ওয়ালেট)",
      "row4Response": "১ কার্যদিন",
      "row4Resolution": "১–৩ কার্যদিন",
      "row5Type": "রিফান্ড (কার্ড/ব্যাংক)",
      "row5Response": "১ কার্যদিন",
      "row5Resolution": "৫–১০ কার্যদিন",
      "row6Type": "ওয়ারেন্টি দাবি",
      "row6Response": "১–২ কার্যদিন",
      "row6Resolution": "৭–২১ কার্যদিন",
      "row7Type": "পেমেন্ট ব্যর্থতার ট্রেস",
      "row7Response": "১ কার্যদিন",
      "row7Resolution": "২–৫ কার্যদিন",
      "faqTitle": "প্রায়ই জিজ্ঞাসিত প্রশ্ন",
      "faq1q": "কীভাবে পণ্য ফেরত দেব?",
      "faq1a": "আমার অর্ডারে যান, অর্ডার নির্বাচন করুন এবং \"রিটার্ন / বিবাদ\" চাপুন। কারণ পূরণ করে জমা দিন। আমাদের দল ১–২ কার্যদিনের মধ্যে পর্যালোচনা করে।",
      "faq2q": "রিফান্ড কখন পাব?",
      "faq2a": "রিটার্ন অনুমোদিত হলে এবং পণ্য পরীক্ষায় পাস করলে মোবাইল ওয়ালেটে ১–৩ কার্যদিনে, কার্ড/ব্যাংকে ৫–১০ দিনে রিফান্ড হয়।",
      "faq3q": "অর্ডার আসেনি। কী করব?",
      "faq3a": "প্রথমে অর্ডার ট্র্যাকিং টাইমলাইন দেখুন। আনুমানিক ডেলিভারি সময় পেরিয়ে গেলে অর্ডার ID সহ সাপোর্ট টিকিট খুলুন।",
      "faq4q": "অর্ডার দেওয়ার পর ডেলিভারি ঠিকানা পরিবর্তন করা যাবে?",
      "faq4a": "শুধুমাত্র ডিসপ্যাচের আগে পরিবর্তন সম্ভব। অর্ডার ID সহ অবিলম্বে সাপোর্টে যোগাযোগ করুন।",
      "faq5q": "পাইকারি অ্যাক্সেসের জন্য আবেদন কীভাবে করব?",
      "faq5a": "পাইকারি হাব পাতায় যান এবং আবেদন ফর্ম পূরণ করুন। আমাদের দল ২–৩ কার্যদিনের মধ্যে আবেদন পর্যালোচনা করে।",
      "faq6q": "কোন পেমেন্ট পদ্ধতি গ্রহণ করা হয়?",
      "faq6a": "বিকাশ, নগদ, রকেট, উপায়, SSLCommerz (কার্ড ও ইন্টারনেট ব্যাংকিং), এবং ক্যাশ অন ডেলিভারি (৳৫,০০০ পর্যন্ত) গ্রহণ করা হয়।",
      "faq7q": "পেমেন্ট ব্যর্থ হয়েছে কিন্তু টাকা কেটেছে। কী হবে?",
      "faq7a": "ব্যর্থ পেমেন্টের কাটা টাকা পেমেন্ট প্রদানকারী ৩–৫ কার্যদিনে ফেরত দেয়। না হলে লেনদেন নম্বর সহ টিকিট খুলুন।",
      "faq8q": "OB পয়েন্ট কীভাবে কাজ করে?",
      "faq8a": "প্রতি ১ টাকায় ১ OB পয়েন্ট অর্জন করুন। চেকআউটে পয়েন্ট রিডিম করে ছাড় পান। ব্রোঞ্জ, সিলভার ও গোল্ড স্তরে ভিন্ন সুবিধা।",
      "stillNeedHelp": "এখনও সাহায্য দরকার?",
      "supportTicketsTitle": "সাপোর্ট টিকিট",
      "supportTicketsDesc": "অর্ডার বিবাদ, পেমেন্ট সমস্যা বা পণ্য অভিযোগের জন্য টিকিট খুলুন। সম্পূর্ণ বার্তার ইতিহাস সংরক্ষিত।",
      "openTicketCta": "টিকিট খুলুন →",
      "policyDocsTitle": "পলিসি ডকুমেন্ট",
      "policyDocsDesc": "রিটার্ন, রিফান্ড, শিপিং, ওয়ারেন্টি ও শর্তাবলি পলিসি পড়ুন।",
      "readPoliciesCta": "পলিসি পড়ুন →"
    },
    "contact": {
      "eyebrow": "যোগাযোগ করুন",
      "title": "Ocean Bazar-এ যোগাযোগ",
      "intro": "অর্ডার, হোলসেল বা পার্টনারশিপ নিয়ে প্রশ্ন? আমাদের টিম বাংলাদেশ জুড়ে সহায়তায় প্রস্তুত।",
      "visionEyebrow": "আমাদের ভিশন",
      "visionTitle": "Ocean Bazar গড়ে তোলা",
      "leadershipEyebrow": "নেতৃত্ব",
      "leadershipTitle": "আমাদের লিডারশিপ টিম",
      "buildingAlt": "Ocean Bazar ওয়্যারহাউস ও লজিস্টিক্স হাব",
      "aboutTitle": "Ocean Bazar সম্পর্কে",
      "aboutBody": "Ocean Bazar বাংলাদেশের বিশ্বস্ত রিটেইল ও হোলসেল ই-কমার্স প্ল্যাটফর্ম — সীমানার বাইরে, প্রজন্ম ধরে গড়ে ওঠা।",
      "aboutBody2": "আমাদের ফুলফিলমেন্ট হাব থেকে রিটেইল, হোলসেল ও ব্র্যান্ড পার্টনারদের জন্য স্বচ্ছ মূল্য, নিরাপদ পেমেন্ট ও নিবেদিত সাপোর্ট।",
      "reachTitle": "যোগাযোগের তথ্য",
      "addressLabel": "ঠিকানা",
      "contactEmailLabel": "যোগাযোগ ইমেইল",
      "businessEmailLabel": "ব্যবসায়িক অনুসন্ধান ইমেইল",
      "phoneLabel": "যোগাযোগ ফোন",
      "chatCta": "লাইভ চ্যাট",
      "businessCta": "ব্যবসায়িক অনুসন্ধান",
      "supportCta": "সাপোর্ট সেন্টার"
    },
    "business": {
      "heroTag": "ব্যবসা ও অংশীদারিত্ব",
      "title": "OceanBazar-এর সাথে পার্টনার হন",
      "subtitle": "আপনি বাল্ক প্রকিউরমেন্ট, কর্পোরেট গিফটিং, রিসেলার পার্টনারশিপ, বা ব্র্যান্ড কোলাবরেশন খুঁজছেন — আমরা আপনার কথা শুনতে চাই।",
      "whyTitle": "কেন আমাদের সাথে পার্টনার হবেন?",
      "whySub": "OceanBazar বাংলাদেশের সকল আকারের ব্যবসাকে সাপোর্ট করার জন্য তৈরি।",
      "feat1Title": "সারাদেশব্যাপী নেটওয়ার্ক",
      "feat1Body": "বাংলাদেশের ৬৪ জেলায় নির্ভরযোগ্য লাস্ট-মাইল ডেলিভারিসহ লজিস্টিক নেটওয়ার্ক।",
      "feat2Title": "পাইকারি মূল্য",
      "feat2Body": "স্বয়ংক্রিয় ভলিউম-ভিত্তিক ডিসকাউন্ট — বেশি অর্ডার করলে বেশি সাশ্রয়।",
      "feat3Title": "যাচাইকৃত মার্কেটপ্লেস",
      "feat3Body": "প্রতিটি বিক্রেতা যাচাইকৃত। পণ্য মান-পরীক্ষিত। প্রতিটি অর্ডারে সম্পূর্ণ ক্রেতা সুরক্ষা।",
      "feat4Title": "ডেডিকেটেড সাপোর্ট",
      "feat4Body": "ব্যবসায়িক অ্যাকাউন্ট প্রায়োরিটি সাপোর্ট কিউ পায় — দ্রুত রেসপন্স টাইম।",
      "feat5Title": "নিরাপদ পেমেন্ট",
      "feat5Body": "সকল লেনদেন এন্ড-টু-এন্ড এনক্রিপ্টেড। বিকাশ, নগদ, SSLCommerz বা ব্যাংক ট্রান্সফারে পে করুন।",
      "feat6Title": "কাস্টম সমাধান",
      "feat6Body": "ব্র্যান্ডেড প্যাকেজিং, শিডিউলড ডেলিভারি বা কাস্টম ক্যাটালগ দরকার? আমরা আপনার প্রয়োজনে সমাধান তৈরি করি।",
      "ctaTitle": "একসাথে বড় হতে প্রস্তুত?",
      "ctaSub": "নিচের ফর্মটি পূরণ করুন এবং আমাদের ব্যবসায়িক টিম ২৪–৪৮ ঘণ্টার মধ্যে যোগাযোগ করবে।",
      "inquiryEmailLabel": "ব্যবসায়িক অনুসন্ধান ইমেইল",
      "contactPageCta": "সাধারণ যোগাযোগের তথ্য",
      "formTitle": "আপনার অনুসন্ধান পাঠান",
      "name": "আপনার নাম",
      "email": "ইমেইল ঠিকানা",
      "company": "প্রতিষ্ঠান / সংস্থা",
      "phone": "ফোন নম্বর",
      "businessType": "ব্যবসার ধরন",
      "businessTypes": {
        "retailer": "খুচরা বিক্রেতা / রিসেলার",
        "corporate": "কর্পোরেট ক্রেতা",
        "brand": "ব্র্যান্ড / প্রস্তুতকারক",
        "wholesale": "পাইকারি পরিবেশক",
        "other": "অন্যান্য"
      },
      "message": "আপনার প্রয়োজন সম্পর্কে বলুন",
      "messagePlaceholder": "আপনার ব্যবসা, প্রত্যাশিত অর্ডার পরিমাণ, পণ্যের আগ্রহ বা পার্টনারশিপ আইডিয়া বর্ণনা করুন…",
      "submit": "অনুসন্ধান পাঠান",
      "success": "ধন্যবাদ! আমাদের ব্যবসায়িক টিম ২৪–৪৮ ঘণ্টার মধ্যে যোগাযোগ করবে।",
      "stat1": "৫০০+",
      "stat1Label": "সক্রিয় ব্যবসায়িক অংশীদার",
      "stat2": "৬৪",
      "stat2Label": "জেলা কভারেজ",
      "stat3": "২৪ ঘণ্টা",
      "stat3Label": "গড় রেসপন্স টাইম",
      "stat4": "৯৮%",
      "stat4Label": "পার্টনার সন্তুষ্টি"
    }
  }
};

function getPageCopy(locale, namespace) {
  const loc = locale === 'bn' ? 'bn' : 'en';
  return (COPY[loc] && COPY[loc][namespace]) || (COPY.en && COPY.en[namespace]) || {};
}

module.exports = { getPageCopy, COPY };
